// Operational Intent Definitions for BisnisSehat WhatsApp Operational System

export const OPERATIONAL_INTENTS = {
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',

  ADD_STOCK: 'ADD_STOCK',
  REDUCE_STOCK: 'REDUCE_STOCK',
  STOCK_TRANSFER: 'STOCK_TRANSFER',

  CREATE_WAREHOUSE: 'CREATE_WAREHOUSE',
  UPDATE_WAREHOUSE: 'UPDATE_WAREHOUSE',
  DELETE_WAREHOUSE: 'DELETE_WAREHOUSE',

  CREATE_SUPPLIER: 'CREATE_SUPPLIER',
  UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
  DELETE_SUPPLIER: 'DELETE_SUPPLIER',

  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',

  CREATE_SALE: 'CREATE_SALE',
  UPDATE_SALE: 'UPDATE_SALE',
  DELETE_SALE: 'DELETE_SALE',
  CREATE_PURCHASE: 'CREATE_PURCHASE',
  UPDATE_PURCHASE: 'UPDATE_PURCHASE',
  DELETE_PURCHASE: 'DELETE_PURCHASE',

  CREATE_EXPENSE: 'CREATE_EXPENSE',
  UPDATE_EXPENSE: 'UPDATE_EXPENSE',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
  CREATE_INCOME: 'CREATE_INCOME',
  UPDATE_INCOME: 'UPDATE_INCOME',
  DELETE_INCOME: 'DELETE_INCOME',

  CREATE_INVOICE: 'CREATE_INVOICE',
  UPDATE_INVOICE: 'UPDATE_INVOICE',
  DELETE_INVOICE: 'DELETE_INVOICE',
  RECORD_PAYMENT: 'RECORD_PAYMENT',
  UPDATE_PAYMENT: 'UPDATE_PAYMENT',
  DELETE_PAYMENT: 'DELETE_PAYMENT',

  SHOW_GREETING: 'SHOW_GREETING',
  SELECT_AI_MODE: 'SELECT_AI_MODE',
  SELECT_FORM_MODE: 'SELECT_FORM_MODE',
  SHOW_MENU: 'SHOW_MENU',
  SHOW_HELP: 'SHOW_HELP',
  UNKNOWN: 'UNKNOWN'
};

export const INTENT_LABELS = {
  [OPERATIONAL_INTENTS.CREATE_PRODUCT]: 'Tambah Produk',
  [OPERATIONAL_INTENTS.ADD_STOCK]: 'Tambah Stok',
  [OPERATIONAL_INTENTS.REDUCE_STOCK]: 'Kurang Stok',
  [OPERATIONAL_INTENTS.STOCK_TRANSFER]: 'Transfer Stok',
  [OPERATIONAL_INTENTS.CREATE_SUPPLIER]: 'Tambah Supplier',
  [OPERATIONAL_INTENTS.CREATE_CUSTOMER]: 'Tambah Pelanggan',
  [OPERATIONAL_INTENTS.CREATE_SALE]: 'Catat Penjualan',
  [OPERATIONAL_INTENTS.CREATE_PURCHASE]: 'Catat Pembelian',
  [OPERATIONAL_INTENTS.CREATE_EXPENSE]: 'Catat Pengeluaran',
  [OPERATIONAL_INTENTS.CREATE_INCOME]: 'Catat Pemasukan',
  [OPERATIONAL_INTENTS.CREATE_INVOICE]: 'Buat Invoice',
  [OPERATIONAL_INTENTS.RECORD_PAYMENT]: 'Bayar Invoice',
  [OPERATIONAL_INTENTS.CREATE_WAREHOUSE]: 'Tambah Gudang',
};
